package com.hasan;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.*;

public class FileChooseAndViewOutput extends javax.swing.JFrame {
    private String filename = null;
    private Store myStore;
    private String searchText = "";


    public FileChooseAndViewOutput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserBtn = new javax.swing.JButton();
        fileLocationTextBox = new javax.swing.JTextField();
        btnMaxOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextBox = new javax.swing.JTextArea();
        allOrdersBtn = new javax.swing.JButton();
        allBooksBtn = new javax.swing.JButton();
        searchTextBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchTextBox.addKeyListener(
                new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        searchText = searchTextBox.getText();
                        searchBtn.setEnabled(filename!=null && !searchTextBox.getText().trim().isEmpty());
                    }
                }
        );

        fileChooserBtn.setText("CHOOSE FILE");
        fileChooserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMaxOrder.setText("MAXIMUM BOOK ORDER");
        btnMaxOrder.setEnabled(filename!=null);
        btnMaxOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxOrderActionPerformed(evt);
            }
        });

        outputTextBox.setColumns(20);
        outputTextBox.setRows(5);
        outputTextBox.setEditable(false);
        outputTextBox.setFont(new Font("Courier", Font.BOLD,25));
        jScrollPane1.setViewportView(outputTextBox);

        allOrdersBtn.setText("ALL ORDERS");
        allOrdersBtn.setEnabled(filename!=null);
        allOrdersBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                allOrdersClick();
            }
        });

        allBooksBtn.setText("ALL BOOKS");
        allBooksBtn.setEnabled(filename!=null);
        allBooksBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                allBooksClick();
            }
        });

        searchBtn.setText("SEARCH BY BOOK NAME");
        searchBtn.setEnabled(filename!=null && !searchTextBox.getText().trim().isEmpty());
        searchBtn.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        searchBtnClick();
                    }
                }
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(fileLocationTextBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fileChooserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(searchTextBox)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 59, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(btnMaxOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(allOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(allBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(searchBtn)
                                                .addGap(10, 10, 10)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fileChooserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fileLocationTextBox))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(searchTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(searchBtn))
                                                .addGap(68, 68, 68)
                                                .addComponent(btnMaxOrder)
                                                .addGap(18, 18, 18)
                                                .addComponent(allOrdersBtn)
                                                .addGap(18, 18, 18)
                                                .addComponent(allBooksBtn)
                                                .addGap(0, 758, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnClick() {
        String output = "";
        Book b = myStore.getBookByTitle(searchText);
        if(b==null)
            output = "No book found!\n";
        else {
            output += b.toString()+"\n\n";
            output += "Total Count: " + myStore.getCountByBookTitle(searchText);
        }
        outputTextBox.setText(output);
    }

    private void allOrdersClick() {
        List<Order> orders = myStore.getOrders();
        String output = "";
        for(Order o : orders){
            output+=o.toString()+"\n\n";
        }
        outputTextBox.setText(output);
    }

    private void allBooksClick() {
        List<Order> orders = myStore.getOrders();
        String output = "";
        for(Order o : orders){
            if(!o.getOrderItem().getType().equals("book"))
                continue;
            output+=o.getOrderItem()+"\n\n";
        }
        outputTextBox.setText(output);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if (f == null)
            return;
        filename = f.getAbsolutePath();
        myStore = Store.builder(filename);
        fileLocationTextBox.setText(filename);
        String fileContent = "";
        updateBtnState();
        try {
            fileContent = new String(Files.readAllBytes(Paths.get(f.getPath())), StandardCharsets.UTF_8);
        } catch (IOException e) {
            e.printStackTrace();
        }
        outputTextBox.setText(fileContent);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateBtnState() {
        searchBtn.setEnabled(filename!=null && !searchTextBox.getText().trim().isEmpty());
        btnMaxOrder.setEnabled(filename!=null);
        allOrdersBtn.setEnabled(filename!=null);
        allBooksBtn.setEnabled(filename!=null);
    }

    private void btnMaxOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxOrderActionPerformed
        Order max = myStore.getOrderWithMaxCount();
        outputTextBox.setText("DETAILS OF MAXIMUM COUNT\nMAXIMUM COUNT " + String.valueOf(max.getCount()) + "\nBOOK TITLE "
                + ((Book)max.getOrderItem()).getTitle() + "\nPRICE " + max.getPrice());
    }//GEN-LAST:event_btnMaxOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooseAndViewOutput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaxOrder;
    private javax.swing.JButton fileChooserBtn;
    private javax.swing.JButton allOrdersBtn;
    private javax.swing.JButton allBooksBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputTextBox;
    private javax.swing.JTextField fileLocationTextBox;
    private javax.swing.JTextField searchTextBox;
    // End of variables declaration//GEN-END:variables


    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public JButton getBtnMaxOrder() {
        return btnMaxOrder;
    }

    public void setBtnMaxOrder(JButton btnMaxOrder) {
        this.btnMaxOrder = btnMaxOrder;
    }

    public JButton getFileChooserBtn() {
        return fileChooserBtn;
    }

    public void setFileChooserBtn(JButton fileChooserBtn) {
        this.fileChooserBtn = fileChooserBtn;
    }

    public JButton getAllOrdersBtn() {
        return allOrdersBtn;
    }

    public void setAllOrdersBtn(JButton allOrdersBtn) {
        this.allOrdersBtn = allOrdersBtn;
    }

    public JButton getAllBooksBtn() {
        return allBooksBtn;
    }

    public void setAllBooksBtn(JButton allBooksBtn) {
        this.allBooksBtn = allBooksBtn;
    }

    public JButton getSearchBtn() {
        return searchBtn;
    }

    public void setSearchBtn(JButton searchBtn) {
        this.searchBtn = searchBtn;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getOutputTextBox() {
        return outputTextBox;
    }

    public void setOutputTextBox(JTextArea outputTextBox) {
        this.outputTextBox = outputTextBox;
    }

    public JTextField getFileLocationTextBox() {
        return fileLocationTextBox;
    }

    public void setFileLocationTextBox(JTextField fileLocationTextBox) {
        this.fileLocationTextBox = fileLocationTextBox;
    }

    public JTextField getSearchTextBox() {
        return searchTextBox;
    }

    public void setSearchTextBox(JTextField searchTextBox) {
        this.searchTextBox = searchTextBox;
    }

    public void showFrame(FileChooseAndViewOutput fcv) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooseAndViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fcv.setVisible(true);
            }
        });
    }

    public Store getMyStore() {
        return myStore;
    }

    public void setMyStore(Store myStore) {
        this.myStore = myStore;
    }
}
